### ISSUE TITLE
# Chủ đề, ngôn ngữ, công cụ (13\03\2024) deadline (17/03/2024)

### ISSUE THREAD

**Issue by quyencanh203** [quyencanh203/App-Software-Engineer#3]
- [ ] chủ đề làm về gì ? 
- [ ] sử dụng ngôn ngữ nào để code?
- [ ] sử dụng công cụ nào (framework  , thư viện, IDE ...)? 
@quyencanh203 @matgoc04

**Comment by quyencanh203** [comment]
cần chọn lịch họp trong tuần

**Comment by matgoc04** [comment]
cuối tuần họp bàn làm giao diện trước
