### ISSUE TITLE
update file Readme (13\03\2024) deadline (17/03/2024)

### ISSUE THREAD

**Issue by quyencanh203** [quyencanh203/App-Software-Engineer#4]
- [ ] đọc [https://topdev.vn/blog/lam-the-nao-de-viet-duoc-mot-file-readme-tot/](url) @matgoc04 
- [ ] tìm thành viên @matgoc04

**Comment by quyencanh203** [comment]
@matgoc04 nhớ làm xong trong tuần nha

**Comment by matgoc04** [comment]
ok
